server:
  port: 8080
  
spring:
  application:
    name: Network Attached Storage

  servlet:
    multipart:
      enabled: true
      max-file-size: 5000MB
      max-request-size: 5000MB

  thymeleaf:
    cache: false