server:
  port: 8080
  
spring:
  application:
    name: Network Attached Storage

  servlet:
    multipart:
      enabled: true
      max-file-size: 4000MB
      max-request-size: 4000MB

  thymeleaf:
    cache: false
    
---

spring:
  profiles: raspberry
  
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB